lista = {
    ""
    "AlphVM": {"site": "http://alphvmmm27o3abo3r2mlmjrpdmzle3rykajqc5xsj7j7ejksbpsa36ad.onion.ws", "conteudo": ""},
    "Arvin Leaks": {"site": "http://3kp6j22pz3zkv76yutctosa6djpj4yib2icvdqxucdaxxedumhqicpad.onion.ws", "conteudo": ""},
    "Atomsilo": {"site": "http://l5cjga2ksw6rxumu5l4xxn3cmahhi2irkbwg3amx6ajroyfmfgpfllid.onion.ws/list.html",
                 "conteudo": ""},
    "AvosLocker": {"site": "http://avosqxh72b5ia23dl5fgwcpndkctuzqvh2iefk5imp3pi5gfhel5klad.onion.ws", "conteudo": ""},
    "BABUK Ransomware": {"site": "http://nq4zyac4ukl4tykmidbzgdlvaboqeqsemkp4t35bzvjeve6zm2lqcjid.onion.ws",
                         "conteudo": ""},
    "BlackByte": {"site": "http://f5uzduboq4fa2xkjloprmctk7ve3dm46ff7aniis66cbekakvksxgeqd.onion.ws", "conteudo": ""},
    "BlackCat": {"site": "http://2cuqgeerjdba2rhdiviezodpu3lc4qz2sjf4qin6f7std2evleqlzjid.onion.ws", "conteudo": ""},
    "BlackMatter Ransomware": {"site": "http://blackmax7su6mbwtcyo3xwtpfxpm356jjqrs34y4crcytpw7mifuedyd.onion.ws",
                               "conteudo": ""},
    "Bonaci Group": {"site": "http://bonacifryrxr4siz6ptvokuihdzmjzpveruklxumflz5thmkgauty2qd.onion.ws",
                     "conteudo": ""},
    "CLOP Leaks": {"site": "http://santat7kpllt6iyvqbr7q4amdv6dzrh6paatvyrzl7ry3zm72zigf4ad.onion.ws", "conteudo": ""},
    "Conti News": {"site": "http://continewsnv5otx5kaoje7krkto2qbu3gtqef22mnr7eaxw3y6ncz3ad.onion.ws", "conteudo": ""},
    "Corporate Leaks": {"site": "http://hxt254aygrsziejn.onion.ws", "conteudo": ""},
    "Cuba": {"site": "http://cuba4ikm4jakjgmkezytyawtdgr2xymvy6nvzgw5cglswg3si76icnqd.onion.ws", "conteudo": ""},
    "Dopple Leaks": {"site": "http://hpoo4dosa3x4ognfxpqcrjwnsigvslm7kv6hvmhh2yqczaxy3j6qnwad.onion.ws",
                     "conteudo": ""},
    "eCh0raix": {"site": "http://veqlxhq7ub5qze3qy56zx2cig2e6tzsgxdspkubwbayqije6oatma6id.onion.ws", "conteudo": ""},
    "Entropy hall of fall": {"site": "http://leaksv7sroztl377bbohzl42i3ddlfsxopcb6355zc7olzigedm5agad.onion.ws/posts",
                             "conteudo": ""},
    "Everest": {"site": "https://ransomocmou6mnbquqz44ewosbkjk3o5qjsl3orawojexfook2j7esad.onion.ws", "conteudo": ""},
    "Grief": {"site": "http://griefcameifmv4hfr3auozmovz5yi6m3h3dwbuqw7baomfxoxz4qteid.onion.ws", "conteudo": ""},
    "Groove [Fake]": {"site": "http://ws3dh6av66sjbxxkjpw5ao3wqzmtejnkzheswm4dz5rrwvular7xvkqd.onion.ws",
                      "conteudo": ""},
    "HARON Ransomware2": {"site": "http://midasbkic5eyfox4dhnijkzc7v7e4hpmsb2qgux7diqbpna4up4rtdad.onion.ws/blog.php",
                          "conteudo": ""},
    "Hive Leaks": {
        "site": "http://hiveapi4nyabjdfz2hxdsr7otrcv6zq6m4rk5i2w7j64lrtny4b7vjad.onion.ws/v1/companies/disclosed",
        "conteudo": ""},
    "HolyGhost": {"site": "http://matmq3z3hiovia3voe2tix2x54sghc3tszj74xgdy4tqtypoycszqzqd.onion.ws", "conteudo": ""},
    "Hotarus Blog Ransomware": {"site": "http://r6d636w47ncnaukrpvlhmtdbvbeltc6enfcuuow3jclpmyga7cz374qd.onion.ws",
                                "conteudo": ""},
    "Karma Leaks": {"site": "http://3nvzqyo6l4wkrzumzu5aod7zbosq4ipgf7ifgj3hsvbcr5vcasordvqd.onion.ws", "conteudo": ""},
    "Lock File Ransomware": {"site": "http://zqaflhty5hyziovsxgqvj2mrz5e5rs6oqxzb54zolccfnvtn5w2johad.onion.ws",
                             "conteudo": ""},
    "LOCKBIT 2.0": {"site": "http://lockbitapt2yfbt7lchxejug47kmqvqqxvvjpqkmevv4l3azl3gy6pyd.onion.ws", "conteudo": ""},
    "LockData Auction": {"site": "http://wm6mbuzipviusuc42kcggzkdpbhuv45sn7olyamy6mcqqked3waslbqd.onion.ws",
                         "conteudo": ""},
    "LOLKEK/GLOBEIMPOSTER": {"site": "http://mmeeiix2ejdwkmseycljetmpiwebdvgjts75c63camjofn2cjdoulzqd.onion.ws",
                             "conteudo": ""},
    "Lorenz": {"site": "http://lorenzmlwpzgxq736jzseuterytjueszsvznuibanxomlpkyxk6ksoyd.onion.ws", "conteudo": ""},
    "LV BLOG": {"site": "http://rbvuetuneohce3ouxjlbxtimyyxokb4btncxjbo44fbgxqy7tskinwad.onion.ws", "conteudo": ""},
    "Marketo": {"site": "http://jvdamsif53dqjycuozlaye2s47p7xij4x6hzwzwhzrqmv36gkyzohhqd.onion.ws", "conteudo": ""},
    "MBC Ransomware": {"site": "http://xembshruusobgbvxg4tcjs3jpdnks6xrr6nbokfxadcnlc53yxir22ad.onion.ws",
                       "conteudo": ""},
    "Moses Staff": {"site": "http://mosesstaffm7hptp.onion.ws", "conteudo": ""},
    "Mount Locker": {"site": "http://mountnewsokhwilx.onion.ws", "conteudo": ""},
    "MY DECRYPTOR": {"site": "http://58b87e60649ccc808ac8mstiejnj.5s4ixqul2enwxrqv.onion.ws", "conteudo": ""},
    "n3tw0rm": {"site": "http://n3twormruynhn3oetmxvasum2miix2jgg56xskdoyihra4wthvlgyeyd.onion.ws", "conteudo": ""},
    "Noname": {"site": "http://vfokxcdzjbpehgit223vzdzwte47l3zcqtafj34qrr26htjo4uf3obid.onion.ws", "conteudo": ""},
    "Pay2Key": {"site": "http://pay2key2zkg7arp3kv3cuugdaqwuesifnbofun4j6yjdw5ry7zw2asid.onion.ws", "conteudo": ""},
    "Payload.bin": {"site": "http://vbmisqjshn4yblehk2vbnil53tlqklxsdaztgphcilto3vdj4geao5qd.onion.ws", "conteudo": ""},
    "Prometheus": {"site": "http://promethw27cbrcot.onion.ws", "conteudo": ""},
    "Pysa": {"site": "http://pysa2bitc5ldeyfak4seeruqymqs4sj5wt5qkcq7aoyg4h2acqieywad.onion.ws/partners.html",
             "conteudo": ""},
    "Quantum Blog": {"site": "http://quantum445bh3gzuyilxdzs5xdepf3b7lkcupswvkryf3n7hgzpxebid.onion.ws",
                     "conteudo": ""},
    "Ragnar Locker": {"site": "http://rgleaktxuey67yrgspmhvtnrqtgogur35lwdrup4d3igtbm3pupc4lyd.onion.ws",
                      "conteudo": ""},
    "Ragnarok": {"site": "http://sushlnty2j7qdzy64qnvyb6ajkwg7resd3p6agc2widnawodtcedgjid.onion.ws", "conteudo": ""},
    "Ransom Support": {"site": "http://d57uremugxjrafyg.onion.ws", "conteudo": ""},
    "RansomEXX": {"site": "http://rnsm777cdsjrsdlbs4v5qoeppu3px6sb2igmh53jzrx7ipcrbjz5b2ad.onion.ws", "conteudo": ""},
    "REvil": {"site": "http://dnpscnbaix6nkwvystl3yxglz7nteicqrou3t75tpcc5532cztc46qyd.onion.ws", "conteudo": ""},
    "Rook": {"site": "http://gamol6n6p2p4c3ad7gxmx3ur7wwdwlywebo2azv3vv5qlmjmole2zbyd.onion.ws", "conteudo": ""},
    "RRansom": {"site": "http://t2tqvp4pctcr7vxhgz5yd5x4ino5tw7jzs3whbntxirhp32djhi7q3id.onion.ws", "conteudo": ""},
    "Sabbath": {"site": "http://54bb47h.blog", "conteudo": ""},
    "Saudi Aramco Leak": {"site": "http://662m7dfcpfsmeetqucdekz3rn4a6dxsxbdjwd6iz3rwnogjsj7i3hxad.onion.ws",
                          "conteudo": ""},
    "Snatch": {"site": "http://hl66646wtlp2naoqnhattngigjp5palgqmbwixepcjyq5i534acgqyad.onion.ws", "conteudo": ""},
    "Spook": {"site": "http://spookuhvfyxzph54ikjfwf2mwmxt572krpom7reyayrmxbkizbvkpaid.onion.ws", "conteudo": ""},
    "SunCrypts": {"site": "http://x2miyuiwpib2imjr5ykyjngdu7v6vprkkhjltrk4qafymtawey4qzwid.onion.ws", "conteudo": ""},
    "synACK / El_Cometa": {"site": "http://xqkz2rmrqkeqf6sjbrb47jfwnqxcd4o2zvaxxzrpbh2piknms37rw2ad.onion.ws",
                           "conteudo": ""},
    "Vice Society": {"site": "http://vsociethok6sbprvevl4dlwbqrzyhxcxaqpvcqt5belwvsuxaxsutyad.onion.ws",
                     "conteudo": ""},
    "Xing Locker": {"site": "http://xingnewj6m4qytljhfwemngm7r7rogrindbq7wrfeepejgxc3bwci7qd.onion.ws", "conteudo": ""}
}
